server:
  port: 8000

eureka:
  client:
    registerWithEureka: false # 是否将自己注册到Eureka服务中， 本身就是所有无需注册
    fetchRegistry: false # 是否从Eureka中获取注册信息
    serviceUrl: # Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://localhost:${server.port}/eureka/
