server:
  port: 8082 # 服务器端口

  mall:
    item:
      url: http://127.0.0.1:/8081/item/

spring:
  application:
    name: mall-microservice-order # 指定服务名

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka/